### ISSUE TITLE
请问可以提供一下dataset吗

### ISSUE THREAD

**Issue by enzo547** [yifang000/QADD#1]
FileNotFoundError: [Errno 2] No such file or directory: '../data/negative.csv

**Comment by yifang000** [comment]
For the positive dataset: [POS](http://www.csbio.sjtu.edu.cn/bioinf/QADD/positive.csv)
For the raw negative dataset: [NEG](http://www.csbio.sjtu.edu.cn/bioinf/QADD/negative.csv), and you may need to preprocess the negative dataset by property filters. (for example, we use QED < 0.605 and SAscore > 2.797)

I hope this helps.

**Comment by enzo547** [comment]
> For the positive dataset: [POS](http://www.csbio.sjtu.edu.cn/bioinf/QADD/positive.csv) For the raw negative dataset: [NEG](http://www.csbio.sjtu.edu.cn/bioinf/QADD/positive.csv), and you may need to preprocess the negative dataset by property filters. (for example, we use QED < 0.605 and SAscore > 2.797)
> 
> I hope this helps.

Thanks for your kind help, but it seems the LINK of NEG data is wrong. Can you share it again?

**Comment by yifang000** [comment]
I have fixed it, thanks for your feedback!

**Comment by junqizeng** [comment]
The two links seem to be wrong again, could you fix it once more?

**Comment by yifang000** [comment]
> The two links seem to be wrong again, could you fix it once more?

Hey, you can access them by running "wget + the download link" as follows:
`wget http://www.csbio.sjtu.edu.cn/bioinf/QADD/positive.csv`
`wget http://www.csbio.sjtu.edu.cn/bioinf/QADD/negative.csv`
