### ISSUE TITLE
The program reports the following error when I run train.py

### ISSUE THREAD

**Issue by 1200Caixia** [yifang000/QADD#3]
The program reports the following error when I run train.py

Traceback (most recent call last):
  File "trainQA.py", line 3, in <module>
    from .dglGIN import *
ImportError: attempted relative import with no known parent package

**Comment by yifang000** [comment]
Please check if the 'dglGIN.py' is in your excute path :)

**Comment by 1200Caixia** [comment]
> Please check if the 'dglGIN.py' is in your excute path :)

dglGIN.py and train.py are in the same path

**Comment by 1200Caixia** [comment]
> Please check if the 'dglGIN.py' is in your excute path :)

The 'dglGIN.py' is actually in my excute path.

**Comment by yifang000** [comment]
Try 'from dglGIN import *' instead?

**Comment by 1200Caixia** [comment]
It can work. Thank you very much.
